services:
  restic:
    image: restic/restic:latest
    container_name: restic
    environment:
      - RESTIC_REPOSITORY=${RESTIC_REPOSITORY}
      - RESTIC_PASSWORD=${RESTIC_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - /backups/gitlab:/backup
      - /backups/restore:/backup/restore
    entrypoint: ["restic"]
    restart: "no"